image: docker:stable

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

build-dashboard:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - |
        mkdir -p /kaniko/.docker
        echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
          /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/dashboard/Dockerfile --destination $CI_COMMIT_SHA
